apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    user: spotify
    secureJsonData:
      password: admin_postgres_123
    jsonData:
      database: spotify_db
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
